#公共配置
server:
  port: 8081

spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://188.131.235.188:3306/task_sys?characterEncoding=UTF-8&serverTimezone=CTT
     username: root
     password: sx890828

  redis:
    cluster:
      nodes: 188.131.235.188:7000,188.131.235.188:7001,188.131.235.188:7002,188.131.235.188:7003,188.131.235.188:7004,188.131.235.188:7005
    password:

#mybatis的配置
mybatis:
  mapper-locations: classpath*:com/sangxiang/dao/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#通用mapper
mapper:
  mappers:
      - com.sangxiang.base.mapper.MyMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#logback日志配置
logging:
  config: classpath:logback-base.xml
  path: logs