#公共配置
server:
  port: 8081

spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/TestDB?characterEncoding=UTF-8
     username: root
     password: sx123456

#mybatis的配置
mybatis:
  mapper-locations: classpath*:com/sangxiang/dao/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#通用mapper
mapper:
  mappers:
      - com.sangxiang.base.mapper.MyMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#logback日志配置
logging:
  config: classpath:logback-base.xml
  path: logs